<a href="https://colab.research.google.com/github/shaid03/Machine-Learning/blob/main/Complete_Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Numpy Basic***

***Numpy --> Numerical Python***

Advantages of Numpy array

1. Allow serval methematical operation

2. Faster operations

In [5]:
# to use numpy we need to import this library
import numpy as np

List vs Numpy --> Time Taken

In [6]:
from time import process_time

Time Taken by List

In [7]:
python_list = [i for i in range(10000000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.9350630820000001


Now do the same process in numpy array

In [8]:
np_array = np.array([i for i in range(10000000)])

start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)

0.014554803999999422


In [9]:
#difference betweeen list and numpy array

#list
list1 = [1,2,3,4,5,6]
print(list1)
type(list1)

#numpy array
np_array = np.array([1,2,3,4,5,6])
print(np_array)
type(np_array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


numpy.ndarray

In [10]:
# create one dimension array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [11]:
# Now print it shape
# the output will be five and here five represent 5 columns
a.shape

(5,)

In [12]:
#Now create two dimension array
b = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
# Now create it shape
# Here the output will be (3, 4), so 3 is the column and 4 is the row
b.shape

(3, 4)

In [14]:
# mention data type
# the default value will be integer

c = np.array([(1,2,3,4),(3,5,24,3)], dtype = float)
print(c)

[[ 1.  2.  3.  4.]
 [ 3.  5. 24.  3.]]


***Initial Placeholder in Numpy Array***

In [15]:
# Create numpy array of Zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# Create numpy array of ones

y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
# Create numpy array of particular values

empt = np.full((6,4), 5)
print(empt)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
# create an identity matrix

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# create a numpy random array

b = np.random.random((3,4))
print(b)

[[0.58791026 0.58660043 0.97290998 0.58823661]
 [0.32606461 0.34952985 0.51090364 0.28659762]
 [0.80815667 0.78897154 0.40378281 0.19255568]]


In [20]:
# create a numpy random integer array with a specific range

c = np.random.randint(10,100, (3,5))
print(c)

[[15 69 53 20 39]
 [87 63 18 23 46]
 [69 18 14 90 86]]


In [21]:
# array of evenly spaced array
d = np.linspace(1,100, 10)
print(d)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [24]:
# array of evenly steped array
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [25]:
#convert list to numpy array

list2 = [1,2,3,4,5,6,7]
numpy_array2 = np.asarray(list2)
print(numpy_array2)

[1 2 3 4 5 6 7]


***Analysing a numpy array***

In [27]:
an = np.random.randint(10,99,(5,5))
print(an)

[[55 94 24 56 60]
 [20 72 77 72 32]
 [80 82 75 15 10]
 [24 72 21 35 89]
 [84 80 31 82 74]]


In [32]:
# array dimensions
print(an.shape)

(5, 5)


In [33]:
#number of dimensions
print(an.ndim)

2


In [35]:
# number of element in array

print(an.size)

25


In [37]:
# checking the data type of the value in array

print(an.dtype)

int64


***Mathematically operation in numpy array***

In [39]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # here it just concatenate the value #not adding the value

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [40]:
# Now do the same process for numpy array

np1 = np.random.randint(0,10,(3,3))
np2 = np.random.randint(10,20,(3,3))

In [42]:
print(np1)
print(np2)

[[8 6 7]
 [0 5 4]
 [9 0 4]]
[[16 13 10]
 [17 18 10]
 [11 13 14]]


In [46]:
print(np1 + np2)
print(np1 - np2)
print(np1 * np2)
print(np1 / np2)

[[24 19 17]
 [17 23 14]
 [20 13 18]]
[[ -8  -7  -3]
 [-17 -13  -6]
 [ -2 -13 -10]]
[[128  78  70]
 [  0  90  40]
 [ 99   0  56]]
[[0.5        0.46153846 0.7       ]
 [0.         0.27777778 0.4       ]
 [0.81818182 0.         0.28571429]]


In [47]:
# now do the same process through numpy functions

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [49]:
print(a)
print(b)

[[7 0 2]
 [3 4 9]
 [2 0 5]]
[[17 10 12]
 [12 10 14]
 [17 14 14]]


In [53]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[24 10 14]
 [15 14 23]
 [19 14 19]]
[[-10 -10 -10]
 [ -9  -6  -5]
 [-15 -14  -9]]
[[119   0  24]
 [ 36  40 126]
 [ 34   0  70]]
[[0.41176471 0.         0.16666667]
 [0.25       0.4        0.64285714]
 [0.11764706 0.         0.35714286]]


***Array Manipulation***

In [59]:
# random array
array = np.random.randint(0,10,(2,3))
print(array)
# random array size
print(np.shape(array))

[[8 3 2]
 [2 9 7]]
(2, 3)


In [58]:
# transpose of the above array

trans = np.transpose(array)
print(trans)
print(np.shape(trans))

[[1 9]
 [3 2]
 [9 7]]
(3, 2)


In [61]:
# another method of trans

trans2 = array.T
print(trans2)
print(np.shape(trans2))

[[8 2]
 [3 9]
 [2 7]]
(3, 2)


In [65]:
# reshape random array
array = np.random.randint(0,10,(2,3))
print(array)
# random array size
print(np.shape(array))

[[3 3 0]
 [5 1 0]]
(2, 3)


In [67]:
# Here i change the shape of the array
reshape_array = array.reshape(3,2)
print(reshape_array)
print(np.shape(reshape_array))

[[3 3]
 [0 5]
 [1 0]]
(3, 2)
