<a href="https://colab.research.google.com/github/shaid03/Machine-Learning/blob/main/Data_preprocessing_steps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Preprocessing

In [48]:
# import libraries
import numpy as np
import pandas as pd

In [49]:
dataset = pd.read_csv('/content/Data.csv')

In [50]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

seperate dependent and independent variable

In [51]:
x = dataset[['Country', 'Age', 'Salary']].values

In [52]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [53]:
y = dataset[['Purchased']].values

In [54]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

Missing data

In [55]:
# to handle missing data we have two method first is to remove the whole row or column
# the second is impute function from sklean
from sklearn.impute import SimpleImputer

In [56]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [57]:
imputer = imputer.fit(x[:,1:3])

In [58]:
x[:,1:3]=imputer.fit_transform(x[:,1:3])

In [59]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Encoding Categorical data

In [60]:
from sklearn.preprocessing import LabelEncoder

In [61]:
label_encoder_x = LabelEncoder()

In [62]:
x[:,0]=label_encoder_x.fit_transform(x[:,0])

In [63]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [64]:
from sklearn.preprocessing import OneHotEncoder

In [65]:
onehotencoder = OneHotEncoder()

In [67]:
x = onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [68]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [69]:
label_encoder_y = LabelEncoder()

In [71]:
y = label_encoder_y.fit_transform(y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [79]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [86]:
from sklearn.model_selection import train_test_split

In [92]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [93]:
x_train

array([[-0.81649658,  1.52752523, -0.65465367],
       [ 1.22474487, -0.65465367, -0.65465367],
       [-0.81649658, -0.65465367,  1.52752523],
       [-0.81649658, -0.65465367,  1.52752523],
       [ 1.22474487, -0.65465367, -0.65465367],
       [-0.81649658, -0.65465367,  1.52752523],
       [ 1.22474487, -0.65465367, -0.65465367],
       [ 1.22474487, -0.65465367, -0.65465367]])

In [94]:
x_test

array([[-0.81649658,  1.52752523, -0.65465367],
       [-0.81649658,  1.52752523, -0.65465367]])

In [96]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [95]:
y_test

array([0, 0])

Feature scaling

In [97]:
from sklearn.preprocessing import StandardScaler

In [98]:
scaler = StandardScaler()

In [99]:
x_train = scaler.fit_transform(x_train)

In [100]:
x_test = scaler.fit_transform(x_test)

In [101]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [102]:
x_test

array([[0., 0., 0.],
       [0., 0., 0.]])