<a href="https://colab.research.google.com/github/shaid03/Machine-Learning/blob/main/Matrix_operation_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import libraries
import numpy as np

In [2]:
A = np.array([[2,3],[4,7]])

In [3]:
B = np.array([[6,7],[9,1]])

In [4]:
print(A)

[[2 3]
 [4 7]]


In [5]:
print(B)

[[6 7]
 [9 1]]


In [6]:
A.shape

(2, 2)

In [7]:
B.shape

(2, 2)

Addition of two matrix

In [8]:
sum = A + B

In [9]:
print(sum)

[[ 8 10]
 [13  8]]


In [10]:
# create a random matrix
C = np.random.randint(100, size = (3,3))
D = np.random.randint(100, size = (3,3))

In [11]:
print(C)

[[12 17 86]
 [48 33 88]
 [99 65  6]]


In [12]:
print(D)

[[71 69 17]
 [ 3 51 85]
 [ 0  6 16]]


In [13]:
C.shape

(3, 3)

In [14]:
D.shape

(3, 3)

In [15]:
sum = np.add(C,D)

In [16]:
print(sum)

[[ 83  86 103]
 [ 51  84 173]
 [ 99  71  22]]


In [17]:
# create a random matrix
E = np.random.randint(100, size = (3,3))
F = np.random.randint(100, size = (3,4))

In [18]:
sum = np.add(E,F)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

***Two matrices, can be added if they have the same shape***

***Matrix Subsraction***

In [19]:
A = np.array([[81,6], [11,4]])
B = np.array([[8,6], [1,41]])

In [20]:
print(A)

[[8 6]
 [1 4]]


In [21]:
print(B)

[[8 6]
 [1 4]]


In [22]:
A.shape

(2, 2)

In [23]:
B.shape

(2, 2)

In [24]:
print(A-B)

[[0 0]
 [0 0]]


In [25]:
A = np.array([[81,6], [11,4]])
B = np.array([[8,6], [1,41]])

In [26]:
difference = np.subtract(A, B)

In [27]:
print(difference)

[[ 73   0]
 [ 10 -37]]


Multplying a matrix by a scalar

In [28]:
x = 5
y = np.random.randint(10, size = (3,3))

In [29]:
product = (x * y)

In [30]:
print(product)

[[10 45  5]
 [35  0 45]
 [20  0 45]]


In [31]:
product = np.multiply(x,y)

In [32]:
print(product)

[[10 45  5]
 [35  0 45]
 [20  0 45]]


Multplying two matrix

In [51]:
x = np.random.randint(10, size = (3,3))
y = np.random.randint(10, size = (3,3))

In [52]:
print(x)

[[5 9 8]
 [2 0 3]
 [0 0 6]]


In [53]:
print(y)

[[5 6 7]
 [6 4 6]
 [4 8 2]]


In [54]:
product = np.dot(x, y)

In [55]:
print(product)

[[111 130 105]
 [ 22  36  20]
 [ 24  48  12]]


Element wise matrix multiplication

In [59]:
x = np.random.randint(10, size = (3,3))
y = np.random.randint(10, size = (3,3))

In [60]:
print(x)

[[9 6 3]
 [9 8 4]
 [9 8 0]]


In [61]:
print(y)

[[9 2 5]
 [9 2 2]
 [4 5 8]]


In [62]:
product = np.multiply(x, y)

In [63]:
print(product)

[[81 12 15]
 [81 16  8]
 [36 40  0]]
