<a href="https://colab.research.google.com/github/shaid03/Machine-Learning/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy***

In [73]:
# import library
import numpy as np

In [74]:
array_1 = np.array([3,6,33,55], np.int8)

In [75]:
array_1

array([ 3,  6, 33, 55], dtype=int8)

In [76]:
array_1 = np.array([[3,6,33,55]])

In [77]:
# Accessing the element at the first row and third column of array_1
array_1[0,2]

33

In [78]:
# Setting the element at the first row and second column of array_1 to the value 55
array_1[0,1] = 55

In [79]:
array_1

array([[ 3, 55, 33, 55]])

***Array creation: convertion from other python structures***

In [80]:
listarray = np.array([[1,2,3], [5,8,5], [8,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [8, 3, 1]])

In [81]:
listarray.dtype

dtype('int64')

In [82]:
listarray.shape

(3, 3)

In [83]:
listarray.size

9

In [84]:
np.array({32,23,23})

array({32, 23}, dtype=object)

In [85]:
zeros = np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
rng = np.arange(15)

In [87]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
lspace = np.linspace(1,5,4)

In [89]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [90]:
emp = np.empty((4,6))
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [91]:
emp_like = np.empty_like(lspace)

In [92]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [93]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [94]:
ide.shape

(45, 45)

In [95]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [96]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [97]:
arr = arr.ravel()

In [98]:
arr.shape

(99,)

In [99]:
x = [[1,2,3], [4,5,6], [7,8,9]]
ar = np.array(x)

In [100]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [102]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [103]:
ar.flat

In [104]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
8
9


In [105]:
ar.ndim

2

In [106]:
ar.size

9

In [107]:
ar.nbytes

72

In [108]:
one = np.array([1,5,88,2,9])

In [109]:
one.argmax()

2

In [110]:
one.argmin()

0

In [111]:
one.argsort()

array([0, 3, 1, 4, 2])

In [112]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
ar.argmin()

0

In [114]:
ar.argmax()

8

In [115]:
ar.argmax(axis = 0)

array([2, 2, 2])

In [116]:
ar.argmax(axis = 1)

array([2, 2, 2])

In [117]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [118]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [120]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
ar2 = np.array([[1,2,3],[4,5,6],[2,3,1]])

In [122]:
ar + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 9, 11, 10]])

In [123]:
ar * ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [14, 24,  9]])

In [124]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [125]:
ar.sum()

45

In [126]:
ar.max()

9

In [127]:
ar.min()

1

In [128]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
np.where(ar>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [130]:
type(np.where(ar>5))

tuple

In [131]:
np.count_nonzero(ar)

9

In [132]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [133]:
import sys

In [134]:
py_ar = [0,4,55,2]

In [135]:
np_ar = np.array(py_ar)

In [136]:
sys.getsizeof(1) * len(py_ar)

112

In [137]:
np_ar.itemsize * np_ar.size

32