<a href="https://colab.research.google.com/github/shaid03/Machine-Learning/blob/main/working_with_matrix_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
# import libraries
import numpy as np

In [22]:
matrix_1 = np.array([[2,5],[6,8]])

In [23]:
print(matrix_1)

[[2 5]
 [6 8]]


In [24]:
matrix_1.shape

(2, 2)

In [25]:
matrix_2 = np.array([[2,5,6],[6,8,9],[3,5,1]])

In [26]:
print(matrix_2)

[[2 5 6]
 [6 8 9]
 [3 5 1]]


In [27]:
matrix_2.shape

(3, 3)

Creating matrices with random values

In [28]:
random_matrix = np.random.rand(3,3)

In [29]:
print(random_matrix)

[[0.19449906 0.74882586 0.13301441]
 [0.624955   0.36762497 0.51174744]
 [0.94604148 0.51495605 0.10863652]]


In [30]:
# create random_matrix with integer values
random_matrix = np.random.randint(100, size = (3,3))

In [31]:
print(random_matrix)

[[ 7  3 72]
 [83 93 73]
 [ 7 37  7]]


In [32]:
matrix_3 = np.ones((3,3))

In [33]:
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
matrix_4 = np.ones((3,3),dtype=int)

In [35]:
print(matrix_4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
# Null matrix or zero matrix

matrix_5 = np.zeros((5,5))

In [37]:
print(matrix_5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Identity matrix

In [42]:
# identity matrix
matrix_6 = np.eye(5,5, dtype= int)

In [43]:
print(matrix_6)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Transpose of matrix

In [45]:
# matrix with random integer value
matrix_7 = np.random.randint(100,size = (5,5))
print(matrix_7)

[[60 20 47 18 12]
 [49  6 88 98 69]
 [10 45 73 12 59]
 [ 2 27 75 29 44]
 [56 40 81 15 21]]


In [46]:
transpose_of_matrix = np.transpose(matrix_7)

In [47]:
print(transpose_of_matrix)

[[60 49 10  2 56]
 [20  6 45 27 40]
 [47 88 73 75 81]
 [18 98 12 29 15]
 [12 69 59 44 21]]
